using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bookstore
{
    /// <summary>
    /// Controller class for TblAuthor
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblAuthorController
    {
        // Preload our schema..
        TblAuthor thisSchemaLoad = new TblAuthor();
        private string authorName = String.Empty;
        protected string AuthorName
        {
            get
            {
				if (authorName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						authorName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						authorName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return authorName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblAuthorCollection FetchAll()
        {
            TblAuthorCollection coll = new TblAuthorCollection();
            Query qry = new Query(TblAuthor.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblAuthorCollection FetchByID(object Id)
        {
            TblAuthorCollection coll = new TblAuthorCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblAuthorCollection FetchByQuery(Query qry)
        {
            TblAuthorCollection coll = new TblAuthorCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblAuthor.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblAuthor.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public TblAuthor Insert(TblAuthor item)
	    {
            item.Save(AuthorName);
            return item;
        }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public TblAuthor Update(TblAuthor item)
	    {
            item.Save(AuthorName);
            return item;
        }

        //public TblAuthor Insert(TblAuthor item)
        //{
        //    throw new NotImplementedException();
        //}
    }
}
