using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bookstore
{
	/// <summary>
	/// Strongly-typed collection for the TblBookPricing class.
	/// </summary>
    [Serializable]
	public partial class TblBookPricingCollection : ActiveList<TblBookPricing, TblBookPricingCollection>
	{	   
		public TblBookPricingCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblBookPricingCollection</returns>
		public TblBookPricingCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblBookPricing o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblBookPricing table.
	/// </summary>
	[Serializable]
	public partial class TblBookPricing : ActiveRecord<TblBookPricing>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblBookPricing()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblBookPricing(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblBookPricing(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblBookPricing(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblBookPricing", TableType.Table, DataService.GetInstance("Bookstore"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "Id";
				colvarId.DataType = DbType.Guid;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = false;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				
						colvarId.DefaultSetting = @"(newid())";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarFromHour = new TableSchema.TableColumn(schema);
				colvarFromHour.ColumnName = "FromHour";
				colvarFromHour.DataType = DbType.AnsiString;
				colvarFromHour.MaxLength = 0;
				colvarFromHour.AutoIncrement = false;
				colvarFromHour.IsNullable = false;
				colvarFromHour.IsPrimaryKey = false;
				colvarFromHour.IsForeignKey = false;
				colvarFromHour.IsReadOnly = false;
				
						colvarFromHour.DefaultSetting = @"('00:00:00')";
				colvarFromHour.ForeignKeyTableName = "";
				schema.Columns.Add(colvarFromHour);
				
				TableSchema.TableColumn colvarToHour = new TableSchema.TableColumn(schema);
				colvarToHour.ColumnName = "ToHour";
				colvarToHour.DataType = DbType.AnsiString;
				colvarToHour.MaxLength = 0;
				colvarToHour.AutoIncrement = false;
				colvarToHour.IsNullable = false;
				colvarToHour.IsPrimaryKey = false;
				colvarToHour.IsForeignKey = false;
				colvarToHour.IsReadOnly = false;
				
						colvarToHour.DefaultSetting = @"('00:00:00')";
				colvarToHour.ForeignKeyTableName = "";
				schema.Columns.Add(colvarToHour);
				
				TableSchema.TableColumn colvarOriginalPrice = new TableSchema.TableColumn(schema);
				colvarOriginalPrice.ColumnName = "OriginalPrice";
				colvarOriginalPrice.DataType = DbType.Decimal;
				colvarOriginalPrice.MaxLength = 0;
				colvarOriginalPrice.AutoIncrement = false;
				colvarOriginalPrice.IsNullable = false;
				colvarOriginalPrice.IsPrimaryKey = false;
				colvarOriginalPrice.IsForeignKey = false;
				colvarOriginalPrice.IsReadOnly = false;
				
						colvarOriginalPrice.DefaultSetting = @"((0))";
				colvarOriginalPrice.ForeignKeyTableName = "";
				schema.Columns.Add(colvarOriginalPrice);
				
				TableSchema.TableColumn colvarSaledPrice = new TableSchema.TableColumn(schema);
				colvarSaledPrice.ColumnName = "SaledPrice";
				colvarSaledPrice.DataType = DbType.Decimal;
				colvarSaledPrice.MaxLength = 0;
				colvarSaledPrice.AutoIncrement = false;
				colvarSaledPrice.IsNullable = false;
				colvarSaledPrice.IsPrimaryKey = false;
				colvarSaledPrice.IsForeignKey = false;
				colvarSaledPrice.IsReadOnly = false;
				
						colvarSaledPrice.DefaultSetting = @"((0))";
				colvarSaledPrice.ForeignKeyTableName = "";
				schema.Columns.Add(colvarSaledPrice);
				
				TableSchema.TableColumn colvarIsActived = new TableSchema.TableColumn(schema);
				colvarIsActived.ColumnName = "IsActived";
				colvarIsActived.DataType = DbType.Boolean;
				colvarIsActived.MaxLength = 0;
				colvarIsActived.AutoIncrement = false;
				colvarIsActived.IsNullable = false;
				colvarIsActived.IsPrimaryKey = false;
				colvarIsActived.IsForeignKey = false;
				colvarIsActived.IsReadOnly = false;
				
						colvarIsActived.DefaultSetting = @"((1))";
				colvarIsActived.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIsActived);
				
				TableSchema.TableColumn colvarIsDeleted = new TableSchema.TableColumn(schema);
				colvarIsDeleted.ColumnName = "IsDeleted";
				colvarIsDeleted.DataType = DbType.Boolean;
				colvarIsDeleted.MaxLength = 0;
				colvarIsDeleted.AutoIncrement = false;
				colvarIsDeleted.IsNullable = false;
				colvarIsDeleted.IsPrimaryKey = false;
				colvarIsDeleted.IsForeignKey = false;
				colvarIsDeleted.IsReadOnly = false;
				
						colvarIsDeleted.DefaultSetting = @"((0))";
				colvarIsDeleted.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIsDeleted);
				
				TableSchema.TableColumn colvarCreatedUser = new TableSchema.TableColumn(schema);
				colvarCreatedUser.ColumnName = "CreatedUser";
				colvarCreatedUser.DataType = DbType.AnsiString;
				colvarCreatedUser.MaxLength = 30;
				colvarCreatedUser.AutoIncrement = false;
				colvarCreatedUser.IsNullable = false;
				colvarCreatedUser.IsPrimaryKey = false;
				colvarCreatedUser.IsForeignKey = false;
				colvarCreatedUser.IsReadOnly = false;
				
						colvarCreatedUser.DefaultSetting = @"('')";
				colvarCreatedUser.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCreatedUser);
				
				TableSchema.TableColumn colvarCreatedDate = new TableSchema.TableColumn(schema);
				colvarCreatedDate.ColumnName = "CreatedDate";
				colvarCreatedDate.DataType = DbType.DateTime;
				colvarCreatedDate.MaxLength = 0;
				colvarCreatedDate.AutoIncrement = false;
				colvarCreatedDate.IsNullable = false;
				colvarCreatedDate.IsPrimaryKey = false;
				colvarCreatedDate.IsForeignKey = false;
				colvarCreatedDate.IsReadOnly = false;
				
						colvarCreatedDate.DefaultSetting = @"(getdate())";
				colvarCreatedDate.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCreatedDate);
				
				TableSchema.TableColumn colvarUpdatedUser = new TableSchema.TableColumn(schema);
				colvarUpdatedUser.ColumnName = "UpdatedUser";
				colvarUpdatedUser.DataType = DbType.AnsiString;
				colvarUpdatedUser.MaxLength = 30;
				colvarUpdatedUser.AutoIncrement = false;
				colvarUpdatedUser.IsNullable = false;
				colvarUpdatedUser.IsPrimaryKey = false;
				colvarUpdatedUser.IsForeignKey = false;
				colvarUpdatedUser.IsReadOnly = false;
				
						colvarUpdatedUser.DefaultSetting = @"('')";
				colvarUpdatedUser.ForeignKeyTableName = "";
				schema.Columns.Add(colvarUpdatedUser);
				
				TableSchema.TableColumn colvarUpdatedDate = new TableSchema.TableColumn(schema);
				colvarUpdatedDate.ColumnName = "UpdatedDate";
				colvarUpdatedDate.DataType = DbType.DateTime;
				colvarUpdatedDate.MaxLength = 0;
				colvarUpdatedDate.AutoIncrement = false;
				colvarUpdatedDate.IsNullable = false;
				colvarUpdatedDate.IsPrimaryKey = false;
				colvarUpdatedDate.IsForeignKey = false;
				colvarUpdatedDate.IsReadOnly = false;
				
						colvarUpdatedDate.DefaultSetting = @"(getdate())";
				colvarUpdatedDate.ForeignKeyTableName = "";
				schema.Columns.Add(colvarUpdatedDate);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["Bookstore"].AddSchema("TblBookPricing",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public Guid Id 
		{
			get { return GetColumnValue<Guid>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("FromHour")]
		[Bindable(true)]
		public string FromHour 
		{
			get { return GetColumnValue<string>(Columns.FromHour); }
			set { SetColumnValue(Columns.FromHour, value); }
		}
		  
		[XmlAttribute("ToHour")]
		[Bindable(true)]
		public string ToHour 
		{
			get { return GetColumnValue<string>(Columns.ToHour); }
			set { SetColumnValue(Columns.ToHour, value); }
		}
		  
		[XmlAttribute("OriginalPrice")]
		[Bindable(true)]
		public decimal OriginalPrice 
		{
			get { return GetColumnValue<decimal>(Columns.OriginalPrice); }
			set { SetColumnValue(Columns.OriginalPrice, value); }
		}
		  
		[XmlAttribute("SaledPrice")]
		[Bindable(true)]
		public decimal SaledPrice 
		{
			get { return GetColumnValue<decimal>(Columns.SaledPrice); }
			set { SetColumnValue(Columns.SaledPrice, value); }
		}
		  
		[XmlAttribute("IsActived")]
		[Bindable(true)]
		public bool IsActived 
		{
			get { return GetColumnValue<bool>(Columns.IsActived); }
			set { SetColumnValue(Columns.IsActived, value); }
		}
		  
		[XmlAttribute("IsDeleted")]
		[Bindable(true)]
		public bool IsDeleted 
		{
			get { return GetColumnValue<bool>(Columns.IsDeleted); }
			set { SetColumnValue(Columns.IsDeleted, value); }
		}
		  
		[XmlAttribute("CreatedUser")]
		[Bindable(true)]
		public string CreatedUser 
		{
			get { return GetColumnValue<string>(Columns.CreatedUser); }
			set { SetColumnValue(Columns.CreatedUser, value); }
		}
		  
		[XmlAttribute("CreatedDate")]
		[Bindable(true)]
		public DateTime CreatedDate 
		{
			get { return GetColumnValue<DateTime>(Columns.CreatedDate); }
			set { SetColumnValue(Columns.CreatedDate, value); }
		}
		  
		[XmlAttribute("UpdatedUser")]
		[Bindable(true)]
		public string UpdatedUser 
		{
			get { return GetColumnValue<string>(Columns.UpdatedUser); }
			set { SetColumnValue(Columns.UpdatedUser, value); }
		}
		  
		[XmlAttribute("UpdatedDate")]
		[Bindable(true)]
		public DateTime UpdatedDate 
		{
			get { return GetColumnValue<DateTime>(Columns.UpdatedDate); }
			set { SetColumnValue(Columns.UpdatedDate, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(Guid varId,string varFromHour,string varToHour,decimal varOriginalPrice,decimal varSaledPrice,bool varIsActived,bool varIsDeleted,string varCreatedUser,DateTime varCreatedDate,string varUpdatedUser,DateTime varUpdatedDate)
		{
			TblBookPricing item = new TblBookPricing();
			
			item.Id = varId;
			
			item.FromHour = varFromHour;
			
			item.ToHour = varToHour;
			
			item.OriginalPrice = varOriginalPrice;
			
			item.SaledPrice = varSaledPrice;
			
			item.IsActived = varIsActived;
			
			item.IsDeleted = varIsDeleted;
			
			item.CreatedUser = varCreatedUser;
			
			item.CreatedDate = varCreatedDate;
			
			item.UpdatedUser = varUpdatedUser;
			
			item.UpdatedDate = varUpdatedDate;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(Guid varId,string varFromHour,string varToHour,decimal varOriginalPrice,decimal varSaledPrice,bool varIsActived,bool varIsDeleted,string varCreatedUser,DateTime varCreatedDate,string varUpdatedUser,DateTime varUpdatedDate)
		{
			TblBookPricing item = new TblBookPricing();
			
				item.Id = varId;
			
				item.FromHour = varFromHour;
			
				item.ToHour = varToHour;
			
				item.OriginalPrice = varOriginalPrice;
			
				item.SaledPrice = varSaledPrice;
			
				item.IsActived = varIsActived;
			
				item.IsDeleted = varIsDeleted;
			
				item.CreatedUser = varCreatedUser;
			
				item.CreatedDate = varCreatedDate;
			
				item.UpdatedUser = varUpdatedUser;
			
				item.UpdatedDate = varUpdatedDate;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn FromHourColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn ToHourColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn OriginalPriceColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn SaledPriceColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn IsActivedColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn IsDeletedColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn CreatedUserColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn CreatedDateColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        public static TableSchema.TableColumn UpdatedUserColumn
        {
            get { return Schema.Columns[9]; }
        }
        
        
        
        public static TableSchema.TableColumn UpdatedDateColumn
        {
            get { return Schema.Columns[10]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"Id";
			 public static string FromHour = @"FromHour";
			 public static string ToHour = @"ToHour";
			 public static string OriginalPrice = @"OriginalPrice";
			 public static string SaledPrice = @"SaledPrice";
			 public static string IsActived = @"IsActived";
			 public static string IsDeleted = @"IsDeleted";
			 public static string CreatedUser = @"CreatedUser";
			 public static string CreatedDate = @"CreatedDate";
			 public static string UpdatedUser = @"UpdatedUser";
			 public static string UpdatedDate = @"UpdatedDate";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
