using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bookstore
{
    /// <summary>
    /// Controller class for TblBookCategoryLinked
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblBookCategoryLinkedController
    {
        // Preload our schema..
        TblBookCategoryLinked thisSchemaLoad = new TblBookCategoryLinked();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblBookCategoryLinkedCollection FetchAll()
        {
            TblBookCategoryLinkedCollection coll = new TblBookCategoryLinkedCollection();
            Query qry = new Query(TblBookCategoryLinked.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblBookCategoryLinkedCollection FetchByID(object Id)
        {
            TblBookCategoryLinkedCollection coll = new TblBookCategoryLinkedCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblBookCategoryLinkedCollection FetchByQuery(Query qry)
        {
            TblBookCategoryLinkedCollection coll = new TblBookCategoryLinkedCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblBookCategoryLinked.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblBookCategoryLinked.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(Guid Id,Guid? CategoryId,Guid? BookId)
	    {
		    TblBookCategoryLinked item = new TblBookCategoryLinked();
		    
            item.Id = Id;
            
            item.CategoryId = CategoryId;
            
            item.BookId = BookId;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(Guid Id,Guid? CategoryId,Guid? BookId)
	    {
		    TblBookCategoryLinked item = new TblBookCategoryLinked();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.CategoryId = CategoryId;
				
			item.BookId = BookId;
				
	        item.Save(UserName);
	    }
    }
}
