using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bookstore
{
    /// <summary>
    /// Controller class for TblBook
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblBookController
    {
        // Preload our schema..
        TblBook thisSchemaLoad = new TblBook();
        private string bookTitle = String.Empty;
        protected string BookTitle
        {
            get
            {
				if (bookTitle.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						bookTitle=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						bookTitle=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return bookTitle;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblBookCollection FetchAll()
        {
            TblBookCollection coll = new TblBookCollection();
            Query qry = new Query(TblBook.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblBookCollection FetchByID(object Id)
        {
            TblBookCollection coll = new TblBookCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblBookCollection FetchByQuery(Query qry)
        {
            TblBookCollection coll = new TblBookCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblBook.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblBook.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public TblBook Insert(TblBook item)
	    {
			item.Save(BookTitle);
			return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public TblBook Update(TblBook item)
	    {
            item.Save(BookTitle);
            return item;
	    }
    }
}
