using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bookstore
{
    /// <summary>
    /// Controller class for TblCategory
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblCategoryController
    {
        // Preload our schema..
        TblCategory thisSchemaLoad = new TblCategory();
        private string categoryName = String.Empty;
        protected string CategoryName
        {
            get
            {
				if (categoryName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						categoryName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						categoryName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return categoryName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblCategoryCollection FetchAll()
        {
            TblCategoryCollection coll = new TblCategoryCollection();
            Query qry = new Query(TblCategory.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblCategoryCollection FetchByID(object Id)
        {
            TblCategoryCollection coll = new TblCategoryCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblCategoryCollection FetchByQuery(Query qry)
        {
            TblCategoryCollection coll = new TblCategoryCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblCategory.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblCategory.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public TblCategory Insert(TblCategory item)
	    {
		    item.Save(CategoryName);
            return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public TblCategory Update(TblCategory item)
	    {
            item.Save(CategoryName);
            return item;
	    }
    }
}
