using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bookstore
{
    /// <summary>
    /// Controller class for TblPublisher
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblPublisherController
    {
        // Preload our schema..
        TblPublisher thisSchemaLoad = new TblPublisher();
        private string publisherName = String.Empty;
        protected string PublisherName
        {
            get
            {
				if (publisherName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						publisherName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						publisherName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return publisherName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblPublisherCollection FetchAll()
        {
            TblPublisherCollection coll = new TblPublisherCollection();
            Query qry = new Query(TblPublisher.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblPublisherCollection FetchByID(object Id)
        {
            TblPublisherCollection coll = new TblPublisherCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblPublisherCollection FetchByQuery(Query qry)
        {
            TblPublisherCollection coll = new TblPublisherCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblPublisher.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblPublisher.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public TblPublisher Insert(TblPublisher item)
	    {
            item.Save(PublisherName);
            return item;
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public TblPublisher Update(TblPublisher item)
	    {
            item.Save(PublisherName);
            return item;
	    }
    }
}
