using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bookstore
{
    /// <summary>
    /// Controller class for TblUserPermissionsLinked
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblUserPermissionsLinkedController
    {
        // Preload our schema..
        TblUserPermissionsLinked thisSchemaLoad = new TblUserPermissionsLinked();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblUserPermissionsLinkedCollection FetchAll()
        {
            TblUserPermissionsLinkedCollection coll = new TblUserPermissionsLinkedCollection();
            Query qry = new Query(TblUserPermissionsLinked.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblUserPermissionsLinkedCollection FetchByID(object Id)
        {
            TblUserPermissionsLinkedCollection coll = new TblUserPermissionsLinkedCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblUserPermissionsLinkedCollection FetchByQuery(Query qry)
        {
            TblUserPermissionsLinkedCollection coll = new TblUserPermissionsLinkedCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblUserPermissionsLinked.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblUserPermissionsLinked.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(Guid Id,Guid UserId,Guid PermissionsId)
	    {
		    TblUserPermissionsLinked item = new TblUserPermissionsLinked();
		    
            item.Id = Id;
            
            item.UserId = UserId;
            
            item.PermissionsId = PermissionsId;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(Guid Id,Guid UserId,Guid PermissionsId)
	    {
		    TblUserPermissionsLinked item = new TblUserPermissionsLinked();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.UserId = UserId;
				
			item.PermissionsId = PermissionsId;
				
	        item.Save(UserName);
	    }
    }
}
