using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bookstore
{
	#region Tables Struct
	public partial struct Tables
	{
		
		public static readonly string TblAuthor = @"TblAuthor";
        
		public static readonly string TblBook = @"TblBook";
        
		public static readonly string TblBookAuthorLinked = @"TblBookAuthorLinked";
        
		public static readonly string TblBookCategoryLinked = @"TblBookCategoryLinked";
        
		public static readonly string TblBookPricing = @"TblBookPricing";
        
		public static readonly string TblCategory = @"TblCategory";
        
		public static readonly string TblCustomer = @"TblCustomer";
        
		public static readonly string TblOrder = @"TblOrder";
        
		public static readonly string TblOrderDetail = @"TblOrderDetail";
        
		public static readonly string TblPermission = @"TblPermissions";
        
		public static readonly string TblPublisher = @"TblPublisher";
        
		public static readonly string TblUser = @"TblUser";
        
		public static readonly string TblUserPermissionsLinked = @"TblUserPermissionsLinked";
        
	}
	#endregion
    #region Schemas
    public partial class Schemas {
		
		public static TableSchema.Table TblAuthor
		{
            get { return DataService.GetSchema("TblAuthor", "Bookstore"); }
		}
        
		public static TableSchema.Table TblBook
		{
            get { return DataService.GetSchema("TblBook", "Bookstore"); }
		}
        
		public static TableSchema.Table TblBookAuthorLinked
		{
            get { return DataService.GetSchema("TblBookAuthorLinked", "Bookstore"); }
		}
        
		public static TableSchema.Table TblBookCategoryLinked
		{
            get { return DataService.GetSchema("TblBookCategoryLinked", "Bookstore"); }
		}
        
		public static TableSchema.Table TblBookPricing
		{
            get { return DataService.GetSchema("TblBookPricing", "Bookstore"); }
		}
        
		public static TableSchema.Table TblCategory
		{
            get { return DataService.GetSchema("TblCategory", "Bookstore"); }
		}
        
		public static TableSchema.Table TblCustomer
		{
            get { return DataService.GetSchema("TblCustomer", "Bookstore"); }
		}
        
		public static TableSchema.Table TblOrder
		{
            get { return DataService.GetSchema("TblOrder", "Bookstore"); }
		}
        
		public static TableSchema.Table TblOrderDetail
		{
            get { return DataService.GetSchema("TblOrderDetail", "Bookstore"); }
		}
        
		public static TableSchema.Table TblPermission
		{
            get { return DataService.GetSchema("TblPermissions", "Bookstore"); }
		}
        
		public static TableSchema.Table TblPublisher
		{
            get { return DataService.GetSchema("TblPublisher", "Bookstore"); }
		}
        
		public static TableSchema.Table TblUser
		{
            get { return DataService.GetSchema("TblUser", "Bookstore"); }
		}
        
		public static TableSchema.Table TblUserPermissionsLinked
		{
            get { return DataService.GetSchema("TblUserPermissionsLinked", "Bookstore"); }
		}
        
	
    }
    #endregion
    #region View Struct
    public partial struct Views 
    {
		
    }
    #endregion
    
    #region Query Factories
	public static partial class DB
	{
        public static DataProvider _provider = DataService.Providers["Bookstore"];
        static ISubSonicRepository _repository;
        public static ISubSonicRepository Repository 
        {
            get 
            {
                if (_repository == null)
                    return new SubSonicRepository(_provider);
                return _repository; 
            }
            set { _repository = value; }
        }
        public static Select SelectAllColumnsFrom<T>() where T : RecordBase<T>, new()
	    {
            return Repository.SelectAllColumnsFrom<T>();
	    }
	    public static Select Select()
	    {
            return Repository.Select();
	    }
	    
		public static Select Select(params string[] columns)
		{
            return Repository.Select(columns);
        }
	    
		public static Select Select(params Aggregate[] aggregates)
		{
            return Repository.Select(aggregates);
        }
   
	    public static Update Update<T>() where T : RecordBase<T>, new()
	    {
            return Repository.Update<T>();
	    }
	    
	    public static Insert Insert()
	    {
            return Repository.Insert();
	    }
	    
	    public static Delete Delete()
	    {
            return Repository.Delete();
	    }
	    
	    public static InlineQuery Query()
	    {
            return Repository.Query();
	    }
	    	    
	    
	}
    #endregion
    
}
#region Databases
public partial struct Databases 
{
	
	public static readonly string Bookstore = @"Bookstore";
    
}
#endregion