using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bookstore
{
	/// <summary>
	/// Strongly-typed collection for the TblAuthor class.
	/// </summary>
    [Serializable]
	public partial class TblAuthorCollection : ActiveList<TblAuthor, TblAuthorCollection>
	{	   
		public TblAuthorCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblAuthorCollection</returns>
		public TblAuthorCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblAuthor o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblAuthor table.
	/// </summary>
	[Serializable]
	public partial class TblAuthor : ActiveRecord<TblAuthor>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblAuthor()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblAuthor(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblAuthor(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblAuthor(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblAuthor", TableType.Table, DataService.GetInstance("Bookstore"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "Id";
				colvarId.DataType = DbType.Guid;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = false;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				
						colvarId.DefaultSetting = @"(newid())";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarAuthorName = new TableSchema.TableColumn(schema);
				colvarAuthorName.ColumnName = "AuthorName";
				colvarAuthorName.DataType = DbType.String;
				colvarAuthorName.MaxLength = 50;
				colvarAuthorName.AutoIncrement = false;
				colvarAuthorName.IsNullable = false;
				colvarAuthorName.IsPrimaryKey = false;
				colvarAuthorName.IsForeignKey = false;
				colvarAuthorName.IsReadOnly = false;
				
						colvarAuthorName.DefaultSetting = @"('')";
				colvarAuthorName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAuthorName);
				
				TableSchema.TableColumn colvarAddress = new TableSchema.TableColumn(schema);
				colvarAddress.ColumnName = "Address";
				colvarAddress.DataType = DbType.String;
				colvarAddress.MaxLength = 50;
				colvarAddress.AutoIncrement = false;
				colvarAddress.IsNullable = false;
				colvarAddress.IsPrimaryKey = false;
				colvarAddress.IsForeignKey = false;
				colvarAddress.IsReadOnly = false;
				
						colvarAddress.DefaultSetting = @"('')";
				colvarAddress.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAddress);
				
				TableSchema.TableColumn colvarBiography = new TableSchema.TableColumn(schema);
				colvarBiography.ColumnName = "Biography";
				colvarBiography.DataType = DbType.String;
				colvarBiography.MaxLength = 100;
				colvarBiography.AutoIncrement = false;
				colvarBiography.IsNullable = false;
				colvarBiography.IsPrimaryKey = false;
				colvarBiography.IsForeignKey = false;
				colvarBiography.IsReadOnly = false;
				
						colvarBiography.DefaultSetting = @"('')";
				colvarBiography.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBiography);
				
				TableSchema.TableColumn colvarPhone = new TableSchema.TableColumn(schema);
				colvarPhone.ColumnName = "Phone";
				colvarPhone.DataType = DbType.String;
				colvarPhone.MaxLength = 50;
				colvarPhone.AutoIncrement = false;
				colvarPhone.IsNullable = false;
				colvarPhone.IsPrimaryKey = false;
				colvarPhone.IsForeignKey = false;
				colvarPhone.IsReadOnly = false;
				
						colvarPhone.DefaultSetting = @"('')";
				colvarPhone.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPhone);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["Bookstore"].AddSchema("TblAuthor",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public Guid Id 
		{
			get { return GetColumnValue<Guid>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("AuthorName")]
		[Bindable(true)]
		public string AuthorName 
		{
			get { return GetColumnValue<string>(Columns.AuthorName); }
			set { SetColumnValue(Columns.AuthorName, value); }
		}
		  
		[XmlAttribute("Address")]
		[Bindable(true)]
		public string Address 
		{
			get { return GetColumnValue<string>(Columns.Address); }
			set { SetColumnValue(Columns.Address, value); }
		}
		  
		[XmlAttribute("Biography")]
		[Bindable(true)]
		public string Biography 
		{
			get { return GetColumnValue<string>(Columns.Biography); }
			set { SetColumnValue(Columns.Biography, value); }
		}
		  
		[XmlAttribute("Phone")]
		[Bindable(true)]
		public string Phone 
		{
			get { return GetColumnValue<string>(Columns.Phone); }
			set { SetColumnValue(Columns.Phone, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(Guid varId,string varAuthorName,string varAddress,string varBiography,string varPhone)
		{
			TblAuthor item = new TblAuthor();
			
			item.Id = varId;
			
			item.AuthorName = varAuthorName;
			
			item.Address = varAddress;
			
			item.Biography = varBiography;
			
			item.Phone = varPhone;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(Guid varId,string varAuthorName,string varAddress,string varBiography,string varPhone)
		{
			TblAuthor item = new TblAuthor();
			
				item.Id = varId;
			
				item.AuthorName = varAuthorName;
			
				item.Address = varAddress;
			
				item.Biography = varBiography;
			
				item.Phone = varPhone;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn AuthorNameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn AddressColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn BiographyColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn PhoneColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"Id";
			 public static string AuthorName = @"AuthorName";
			 public static string Address = @"Address";
			 public static string Biography = @"Biography";
			 public static string Phone = @"Phone";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
