using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bookstore
{
	/// <summary>
	/// Strongly-typed collection for the TblCustomer class.
	/// </summary>
    [Serializable]
	public partial class TblCustomerCollection : ActiveList<TblCustomer, TblCustomerCollection>
	{	   
		public TblCustomerCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblCustomerCollection</returns>
		public TblCustomerCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblCustomer o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblCustomer table.
	/// </summary>
	[Serializable]
	public partial class TblCustomer : ActiveRecord<TblCustomer>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblCustomer()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblCustomer(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblCustomer(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblCustomer(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblCustomer", TableType.Table, DataService.GetInstance("Bookstore"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "Id";
				colvarId.DataType = DbType.Guid;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = false;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				
						colvarId.DefaultSetting = @"(newid())";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarCode = new TableSchema.TableColumn(schema);
				colvarCode.ColumnName = "Code";
				colvarCode.DataType = DbType.Guid;
				colvarCode.MaxLength = 0;
				colvarCode.AutoIncrement = false;
				colvarCode.IsNullable = true;
				colvarCode.IsPrimaryKey = false;
				colvarCode.IsForeignKey = false;
				colvarCode.IsReadOnly = false;
				
						colvarCode.DefaultSetting = @"(newid())";
				colvarCode.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCode);
				
				TableSchema.TableColumn colvarFullName = new TableSchema.TableColumn(schema);
				colvarFullName.ColumnName = "FullName";
				colvarFullName.DataType = DbType.String;
				colvarFullName.MaxLength = 100;
				colvarFullName.AutoIncrement = false;
				colvarFullName.IsNullable = false;
				colvarFullName.IsPrimaryKey = false;
				colvarFullName.IsForeignKey = false;
				colvarFullName.IsReadOnly = false;
				
						colvarFullName.DefaultSetting = @"('')";
				colvarFullName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarFullName);
				
				TableSchema.TableColumn colvarEmail = new TableSchema.TableColumn(schema);
				colvarEmail.ColumnName = "Email";
				colvarEmail.DataType = DbType.AnsiString;
				colvarEmail.MaxLength = 100;
				colvarEmail.AutoIncrement = false;
				colvarEmail.IsNullable = false;
				colvarEmail.IsPrimaryKey = false;
				colvarEmail.IsForeignKey = false;
				colvarEmail.IsReadOnly = false;
				
						colvarEmail.DefaultSetting = @"('')";
				colvarEmail.ForeignKeyTableName = "";
				schema.Columns.Add(colvarEmail);
				
				TableSchema.TableColumn colvarPhone = new TableSchema.TableColumn(schema);
				colvarPhone.ColumnName = "Phone";
				colvarPhone.DataType = DbType.AnsiString;
				colvarPhone.MaxLength = 20;
				colvarPhone.AutoIncrement = false;
				colvarPhone.IsNullable = false;
				colvarPhone.IsPrimaryKey = false;
				colvarPhone.IsForeignKey = false;
				colvarPhone.IsReadOnly = false;
				
						colvarPhone.DefaultSetting = @"('')";
				colvarPhone.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPhone);
				
				TableSchema.TableColumn colvarSex = new TableSchema.TableColumn(schema);
				colvarSex.ColumnName = "Sex";
				colvarSex.DataType = DbType.Boolean;
				colvarSex.MaxLength = 0;
				colvarSex.AutoIncrement = false;
				colvarSex.IsNullable = false;
				colvarSex.IsPrimaryKey = false;
				colvarSex.IsForeignKey = false;
				colvarSex.IsReadOnly = false;
				
						colvarSex.DefaultSetting = @"((0))";
				colvarSex.ForeignKeyTableName = "";
				schema.Columns.Add(colvarSex);
				
				TableSchema.TableColumn colvarBirthday = new TableSchema.TableColumn(schema);
				colvarBirthday.ColumnName = "Birthday";
				colvarBirthday.DataType = DbType.DateTime;
				colvarBirthday.MaxLength = 0;
				colvarBirthday.AutoIncrement = false;
				colvarBirthday.IsNullable = false;
				colvarBirthday.IsPrimaryKey = false;
				colvarBirthday.IsForeignKey = false;
				colvarBirthday.IsReadOnly = false;
				
						colvarBirthday.DefaultSetting = @"(getdate())";
				colvarBirthday.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBirthday);
				
				TableSchema.TableColumn colvarUserName = new TableSchema.TableColumn(schema);
				colvarUserName.ColumnName = "UserName";
				colvarUserName.DataType = DbType.AnsiString;
				colvarUserName.MaxLength = 255;
				colvarUserName.AutoIncrement = false;
				colvarUserName.IsNullable = false;
				colvarUserName.IsPrimaryKey = false;
				colvarUserName.IsForeignKey = false;
				colvarUserName.IsReadOnly = false;
				
						colvarUserName.DefaultSetting = @"('')";
				colvarUserName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarUserName);
				
				TableSchema.TableColumn colvarCustomerPassword = new TableSchema.TableColumn(schema);
				colvarCustomerPassword.ColumnName = "CustomerPassword";
				colvarCustomerPassword.DataType = DbType.AnsiString;
				colvarCustomerPassword.MaxLength = 250;
				colvarCustomerPassword.AutoIncrement = false;
				colvarCustomerPassword.IsNullable = false;
				colvarCustomerPassword.IsPrimaryKey = false;
				colvarCustomerPassword.IsForeignKey = false;
				colvarCustomerPassword.IsReadOnly = false;
				
						colvarCustomerPassword.DefaultSetting = @"('')";
				colvarCustomerPassword.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCustomerPassword);
				
				TableSchema.TableColumn colvarIsActived = new TableSchema.TableColumn(schema);
				colvarIsActived.ColumnName = "IsActived";
				colvarIsActived.DataType = DbType.Boolean;
				colvarIsActived.MaxLength = 0;
				colvarIsActived.AutoIncrement = false;
				colvarIsActived.IsNullable = false;
				colvarIsActived.IsPrimaryKey = false;
				colvarIsActived.IsForeignKey = false;
				colvarIsActived.IsReadOnly = false;
				
						colvarIsActived.DefaultSetting = @"((1))";
				colvarIsActived.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIsActived);
				
				TableSchema.TableColumn colvarIsDeleted = new TableSchema.TableColumn(schema);
				colvarIsDeleted.ColumnName = "IsDeleted";
				colvarIsDeleted.DataType = DbType.Boolean;
				colvarIsDeleted.MaxLength = 0;
				colvarIsDeleted.AutoIncrement = false;
				colvarIsDeleted.IsNullable = false;
				colvarIsDeleted.IsPrimaryKey = false;
				colvarIsDeleted.IsForeignKey = false;
				colvarIsDeleted.IsReadOnly = false;
				
						colvarIsDeleted.DefaultSetting = @"((0))";
				colvarIsDeleted.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIsDeleted);
				
				TableSchema.TableColumn colvarAvatar = new TableSchema.TableColumn(schema);
				colvarAvatar.ColumnName = "Avatar";
				colvarAvatar.DataType = DbType.AnsiString;
				colvarAvatar.MaxLength = 255;
				colvarAvatar.AutoIncrement = false;
				colvarAvatar.IsNullable = false;
				colvarAvatar.IsPrimaryKey = false;
				colvarAvatar.IsForeignKey = false;
				colvarAvatar.IsReadOnly = false;
				
						colvarAvatar.DefaultSetting = @"('')";
				colvarAvatar.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAvatar);
				
				TableSchema.TableColumn colvarCreatedUser = new TableSchema.TableColumn(schema);
				colvarCreatedUser.ColumnName = "CreatedUser";
				colvarCreatedUser.DataType = DbType.AnsiString;
				colvarCreatedUser.MaxLength = 30;
				colvarCreatedUser.AutoIncrement = false;
				colvarCreatedUser.IsNullable = false;
				colvarCreatedUser.IsPrimaryKey = false;
				colvarCreatedUser.IsForeignKey = false;
				colvarCreatedUser.IsReadOnly = false;
				
						colvarCreatedUser.DefaultSetting = @"('')";
				colvarCreatedUser.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCreatedUser);
				
				TableSchema.TableColumn colvarCreatedDate = new TableSchema.TableColumn(schema);
				colvarCreatedDate.ColumnName = "CreatedDate";
				colvarCreatedDate.DataType = DbType.DateTime;
				colvarCreatedDate.MaxLength = 0;
				colvarCreatedDate.AutoIncrement = false;
				colvarCreatedDate.IsNullable = false;
				colvarCreatedDate.IsPrimaryKey = false;
				colvarCreatedDate.IsForeignKey = false;
				colvarCreatedDate.IsReadOnly = false;
				
						colvarCreatedDate.DefaultSetting = @"(getdate())";
				colvarCreatedDate.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCreatedDate);
				
				TableSchema.TableColumn colvarUpdatedUser = new TableSchema.TableColumn(schema);
				colvarUpdatedUser.ColumnName = "UpdatedUser";
				colvarUpdatedUser.DataType = DbType.AnsiString;
				colvarUpdatedUser.MaxLength = 30;
				colvarUpdatedUser.AutoIncrement = false;
				colvarUpdatedUser.IsNullable = false;
				colvarUpdatedUser.IsPrimaryKey = false;
				colvarUpdatedUser.IsForeignKey = false;
				colvarUpdatedUser.IsReadOnly = false;
				
						colvarUpdatedUser.DefaultSetting = @"('')";
				colvarUpdatedUser.ForeignKeyTableName = "";
				schema.Columns.Add(colvarUpdatedUser);
				
				TableSchema.TableColumn colvarUpdatedDate = new TableSchema.TableColumn(schema);
				colvarUpdatedDate.ColumnName = "UpdatedDate";
				colvarUpdatedDate.DataType = DbType.DateTime;
				colvarUpdatedDate.MaxLength = 0;
				colvarUpdatedDate.AutoIncrement = false;
				colvarUpdatedDate.IsNullable = false;
				colvarUpdatedDate.IsPrimaryKey = false;
				colvarUpdatedDate.IsForeignKey = false;
				colvarUpdatedDate.IsReadOnly = false;
				
						colvarUpdatedDate.DefaultSetting = @"(getdate())";
				colvarUpdatedDate.ForeignKeyTableName = "";
				schema.Columns.Add(colvarUpdatedDate);
				
				TableSchema.TableColumn colvarCustomerAddress = new TableSchema.TableColumn(schema);
				colvarCustomerAddress.ColumnName = "CustomerAddress";
				colvarCustomerAddress.DataType = DbType.String;
				colvarCustomerAddress.MaxLength = 500;
				colvarCustomerAddress.AutoIncrement = false;
				colvarCustomerAddress.IsNullable = false;
				colvarCustomerAddress.IsPrimaryKey = false;
				colvarCustomerAddress.IsForeignKey = false;
				colvarCustomerAddress.IsReadOnly = false;
				
						colvarCustomerAddress.DefaultSetting = @"('')";
				colvarCustomerAddress.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCustomerAddress);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["Bookstore"].AddSchema("TblCustomer",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public Guid Id 
		{
			get { return GetColumnValue<Guid>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("Code")]
		[Bindable(true)]
		public Guid? Code 
		{
			get { return GetColumnValue<Guid?>(Columns.Code); }
			set { SetColumnValue(Columns.Code, value); }
		}
		  
		[XmlAttribute("FullName")]
		[Bindable(true)]
		public string FullName 
		{
			get { return GetColumnValue<string>(Columns.FullName); }
			set { SetColumnValue(Columns.FullName, value); }
		}
		  
		[XmlAttribute("Email")]
		[Bindable(true)]
		public string Email 
		{
			get { return GetColumnValue<string>(Columns.Email); }
			set { SetColumnValue(Columns.Email, value); }
		}
		  
		[XmlAttribute("Phone")]
		[Bindable(true)]
		public string Phone 
		{
			get { return GetColumnValue<string>(Columns.Phone); }
			set { SetColumnValue(Columns.Phone, value); }
		}
		  
		[XmlAttribute("Sex")]
		[Bindable(true)]
		public bool Sex 
		{
			get { return GetColumnValue<bool>(Columns.Sex); }
			set { SetColumnValue(Columns.Sex, value); }
		}
		  
		[XmlAttribute("Birthday")]
		[Bindable(true)]
		public DateTime Birthday 
		{
			get { return GetColumnValue<DateTime>(Columns.Birthday); }
			set { SetColumnValue(Columns.Birthday, value); }
		}
		  
		[XmlAttribute("UserName")]
		[Bindable(true)]
		public string UserName 
		{
			get { return GetColumnValue<string>(Columns.UserName); }
			set { SetColumnValue(Columns.UserName, value); }
		}
		  
		[XmlAttribute("CustomerPassword")]
		[Bindable(true)]
		public string CustomerPassword 
		{
			get { return GetColumnValue<string>(Columns.CustomerPassword); }
			set { SetColumnValue(Columns.CustomerPassword, value); }
		}
		  
		[XmlAttribute("IsActived")]
		[Bindable(true)]
		public bool IsActived 
		{
			get { return GetColumnValue<bool>(Columns.IsActived); }
			set { SetColumnValue(Columns.IsActived, value); }
		}
		  
		[XmlAttribute("IsDeleted")]
		[Bindable(true)]
		public bool IsDeleted 
		{
			get { return GetColumnValue<bool>(Columns.IsDeleted); }
			set { SetColumnValue(Columns.IsDeleted, value); }
		}
		  
		[XmlAttribute("Avatar")]
		[Bindable(true)]
		public string Avatar 
		{
			get { return GetColumnValue<string>(Columns.Avatar); }
			set { SetColumnValue(Columns.Avatar, value); }
		}
		  
		[XmlAttribute("CreatedUser")]
		[Bindable(true)]
		public string CreatedUser 
		{
			get { return GetColumnValue<string>(Columns.CreatedUser); }
			set { SetColumnValue(Columns.CreatedUser, value); }
		}
		  
		[XmlAttribute("CreatedDate")]
		[Bindable(true)]
		public DateTime CreatedDate 
		{
			get { return GetColumnValue<DateTime>(Columns.CreatedDate); }
			set { SetColumnValue(Columns.CreatedDate, value); }
		}
		  
		[XmlAttribute("UpdatedUser")]
		[Bindable(true)]
		public string UpdatedUser 
		{
			get { return GetColumnValue<string>(Columns.UpdatedUser); }
			set { SetColumnValue(Columns.UpdatedUser, value); }
		}
		  
		[XmlAttribute("UpdatedDate")]
		[Bindable(true)]
		public DateTime UpdatedDate 
		{
			get { return GetColumnValue<DateTime>(Columns.UpdatedDate); }
			set { SetColumnValue(Columns.UpdatedDate, value); }
		}
		  
		[XmlAttribute("CustomerAddress")]
		[Bindable(true)]
		public string CustomerAddress 
		{
			get { return GetColumnValue<string>(Columns.CustomerAddress); }
			set { SetColumnValue(Columns.CustomerAddress, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(Guid varId,Guid? varCode,string varFullName,string varEmail,string varPhone,bool varSex,DateTime varBirthday,string varUserName,string varCustomerPassword,bool varIsActived,bool varIsDeleted,string varAvatar,string varCreatedUser,DateTime varCreatedDate,string varUpdatedUser,DateTime varUpdatedDate,string varCustomerAddress)
		{
			TblCustomer item = new TblCustomer();
			
			item.Id = varId;
			
			item.Code = varCode;
			
			item.FullName = varFullName;
			
			item.Email = varEmail;
			
			item.Phone = varPhone;
			
			item.Sex = varSex;
			
			item.Birthday = varBirthday;
			
			item.UserName = varUserName;
			
			item.CustomerPassword = varCustomerPassword;
			
			item.IsActived = varIsActived;
			
			item.IsDeleted = varIsDeleted;
			
			item.Avatar = varAvatar;
			
			item.CreatedUser = varCreatedUser;
			
			item.CreatedDate = varCreatedDate;
			
			item.UpdatedUser = varUpdatedUser;
			
			item.UpdatedDate = varUpdatedDate;
			
			item.CustomerAddress = varCustomerAddress;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(Guid varId,Guid? varCode,string varFullName,string varEmail,string varPhone,bool varSex,DateTime varBirthday,string varUserName,string varCustomerPassword,bool varIsActived,bool varIsDeleted,string varAvatar,string varCreatedUser,DateTime varCreatedDate,string varUpdatedUser,DateTime varUpdatedDate,string varCustomerAddress)
		{
			TblCustomer item = new TblCustomer();
			
				item.Id = varId;
			
				item.Code = varCode;
			
				item.FullName = varFullName;
			
				item.Email = varEmail;
			
				item.Phone = varPhone;
			
				item.Sex = varSex;
			
				item.Birthday = varBirthday;
			
				item.UserName = varUserName;
			
				item.CustomerPassword = varCustomerPassword;
			
				item.IsActived = varIsActived;
			
				item.IsDeleted = varIsDeleted;
			
				item.Avatar = varAvatar;
			
				item.CreatedUser = varCreatedUser;
			
				item.CreatedDate = varCreatedDate;
			
				item.UpdatedUser = varUpdatedUser;
			
				item.UpdatedDate = varUpdatedDate;
			
				item.CustomerAddress = varCustomerAddress;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn CodeColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn FullNameColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn EmailColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn PhoneColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn SexColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn BirthdayColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn UserNameColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn CustomerPasswordColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        public static TableSchema.TableColumn IsActivedColumn
        {
            get { return Schema.Columns[9]; }
        }
        
        
        
        public static TableSchema.TableColumn IsDeletedColumn
        {
            get { return Schema.Columns[10]; }
        }
        
        
        
        public static TableSchema.TableColumn AvatarColumn
        {
            get { return Schema.Columns[11]; }
        }
        
        
        
        public static TableSchema.TableColumn CreatedUserColumn
        {
            get { return Schema.Columns[12]; }
        }
        
        
        
        public static TableSchema.TableColumn CreatedDateColumn
        {
            get { return Schema.Columns[13]; }
        }
        
        
        
        public static TableSchema.TableColumn UpdatedUserColumn
        {
            get { return Schema.Columns[14]; }
        }
        
        
        
        public static TableSchema.TableColumn UpdatedDateColumn
        {
            get { return Schema.Columns[15]; }
        }
        
        
        
        public static TableSchema.TableColumn CustomerAddressColumn
        {
            get { return Schema.Columns[16]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"Id";
			 public static string Code = @"Code";
			 public static string FullName = @"FullName";
			 public static string Email = @"Email";
			 public static string Phone = @"Phone";
			 public static string Sex = @"Sex";
			 public static string Birthday = @"Birthday";
			 public static string UserName = @"UserName";
			 public static string CustomerPassword = @"CustomerPassword";
			 public static string IsActived = @"IsActived";
			 public static string IsDeleted = @"IsDeleted";
			 public static string Avatar = @"Avatar";
			 public static string CreatedUser = @"CreatedUser";
			 public static string CreatedDate = @"CreatedDate";
			 public static string UpdatedUser = @"UpdatedUser";
			 public static string UpdatedDate = @"UpdatedDate";
			 public static string CustomerAddress = @"CustomerAddress";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
