using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bookstore
{
    /// <summary>
    /// Controller class for TblCustomer
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblCustomerController
    {
        // Preload our schema..
        TblCustomer thisSchemaLoad = new TblCustomer();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblCustomerCollection FetchAll()
        {
            TblCustomerCollection coll = new TblCustomerCollection();
            Query qry = new Query(TblCustomer.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblCustomerCollection FetchByID(object Id)
        {
            TblCustomerCollection coll = new TblCustomerCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblCustomerCollection FetchByQuery(Query qry)
        {
            TblCustomerCollection coll = new TblCustomerCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblCustomer.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblCustomer.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(Guid Id,Guid? Code,string FullName,string Email,string Phone,bool Sex,DateTime Birthday,string UserName,string CustomerPassword,bool IsActived,bool IsDeleted,string Avatar,string CreatedUser,DateTime CreatedDate,string UpdatedUser,DateTime UpdatedDate,string CustomerAddress)
	    {
		    TblCustomer item = new TblCustomer();
		    
            item.Id = Id;
            
            item.Code = Code;
            
            item.FullName = FullName;
            
            item.Email = Email;
            
            item.Phone = Phone;
            
            item.Sex = Sex;
            
            item.Birthday = Birthday;
            
            item.UserName = UserName;
            
            item.CustomerPassword = CustomerPassword;
            
            item.IsActived = IsActived;
            
            item.IsDeleted = IsDeleted;
            
            item.Avatar = Avatar;
            
            item.CreatedUser = CreatedUser;
            
            item.CreatedDate = CreatedDate;
            
            item.UpdatedUser = UpdatedUser;
            
            item.UpdatedDate = UpdatedDate;
            
            item.CustomerAddress = CustomerAddress;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(Guid Id,Guid? Code,string FullName,string Email,string Phone,bool Sex,DateTime Birthday,string UserName,string CustomerPassword,bool IsActived,bool IsDeleted,string Avatar,string CreatedUser,DateTime CreatedDate,string UpdatedUser,DateTime UpdatedDate,string CustomerAddress)
	    {
		    TblCustomer item = new TblCustomer();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Code = Code;
				
			item.FullName = FullName;
				
			item.Email = Email;
				
			item.Phone = Phone;
				
			item.Sex = Sex;
				
			item.Birthday = Birthday;
				
			item.UserName = UserName;
				
			item.CustomerPassword = CustomerPassword;
				
			item.IsActived = IsActived;
				
			item.IsDeleted = IsDeleted;
				
			item.Avatar = Avatar;
				
			item.CreatedUser = CreatedUser;
				
			item.CreatedDate = CreatedDate;
				
			item.UpdatedUser = UpdatedUser;
				
			item.UpdatedDate = UpdatedDate;
				
			item.CustomerAddress = CustomerAddress;
				
	        item.Save(UserName);
	    }
    }
}
