using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bookstore
{
    /// <summary>
    /// Controller class for TblOrder
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblOrderController
    {
        // Preload our schema..
        TblOrder thisSchemaLoad = new TblOrder();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblOrderCollection FetchAll()
        {
            TblOrderCollection coll = new TblOrderCollection();
            Query qry = new Query(TblOrder.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblOrderCollection FetchByID(object Id)
        {
            TblOrderCollection coll = new TblOrderCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblOrderCollection FetchByQuery(Query qry)
        {
            TblOrderCollection coll = new TblOrderCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblOrder.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblOrder.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(Guid Id,DateTime OrderDate,DateTime? DeliveryDate,Guid CustomerId,decimal Discount,decimal TotalPrice,decimal PaymentPrice,decimal PaidPrice,string OrderStatus,string Note,bool IsDeleted,string UpdatedUser,DateTime UpdatedDate)
	    {
		    TblOrder item = new TblOrder();
		    
            item.Id = Id;
            
            item.OrderDate = OrderDate;
            
            item.DeliveryDate = DeliveryDate;
            
            item.CustomerId = CustomerId;
            
            item.Discount = Discount;
            
            item.TotalPrice = TotalPrice;
            
            item.PaymentPrice = PaymentPrice;
            
            item.PaidPrice = PaidPrice;
            
            item.OrderStatus = OrderStatus;
            
            item.Note = Note;
            
            item.IsDeleted = IsDeleted;
            
            item.UpdatedUser = UpdatedUser;
            
            item.UpdatedDate = UpdatedDate;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(Guid Id,DateTime OrderDate,DateTime? DeliveryDate,Guid CustomerId,decimal Discount,decimal TotalPrice,decimal PaymentPrice,decimal PaidPrice,string OrderStatus,string Note,bool IsDeleted,string UpdatedUser,DateTime UpdatedDate)
	    {
		    TblOrder item = new TblOrder();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.OrderDate = OrderDate;
				
			item.DeliveryDate = DeliveryDate;
				
			item.CustomerId = CustomerId;
				
			item.Discount = Discount;
				
			item.TotalPrice = TotalPrice;
				
			item.PaymentPrice = PaymentPrice;
				
			item.PaidPrice = PaidPrice;
				
			item.OrderStatus = OrderStatus;
				
			item.Note = Note;
				
			item.IsDeleted = IsDeleted;
				
			item.UpdatedUser = UpdatedUser;
				
			item.UpdatedDate = UpdatedDate;
				
	        item.Save(UserName);
	    }
    }
}
