using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bookstore
{
	/// <summary>
	/// Strongly-typed collection for the TblPermission class.
	/// </summary>
    [Serializable]
	public partial class TblPermissionCollection : ActiveList<TblPermission, TblPermissionCollection>
	{	   
		public TblPermissionCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblPermissionCollection</returns>
		public TblPermissionCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblPermission o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblPermissions table.
	/// </summary>
	[Serializable]
	public partial class TblPermission : ActiveRecord<TblPermission>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblPermission()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblPermission(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblPermission(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblPermission(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblPermissions", TableType.Table, DataService.GetInstance("Bookstore"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "Id";
				colvarId.DataType = DbType.Guid;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = false;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				
						colvarId.DefaultSetting = @"(newid())";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarPermissionsName = new TableSchema.TableColumn(schema);
				colvarPermissionsName.ColumnName = "PermissionsName";
				colvarPermissionsName.DataType = DbType.String;
				colvarPermissionsName.MaxLength = 100;
				colvarPermissionsName.AutoIncrement = false;
				colvarPermissionsName.IsNullable = false;
				colvarPermissionsName.IsPrimaryKey = false;
				colvarPermissionsName.IsForeignKey = false;
				colvarPermissionsName.IsReadOnly = false;
				
						colvarPermissionsName.DefaultSetting = @"('')";
				colvarPermissionsName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPermissionsName);
				
				TableSchema.TableColumn colvarActionName = new TableSchema.TableColumn(schema);
				colvarActionName.ColumnName = "ActionName";
				colvarActionName.DataType = DbType.Byte;
				colvarActionName.MaxLength = 0;
				colvarActionName.AutoIncrement = false;
				colvarActionName.IsNullable = false;
				colvarActionName.IsPrimaryKey = false;
				colvarActionName.IsForeignKey = false;
				colvarActionName.IsReadOnly = false;
				
						colvarActionName.DefaultSetting = @"((0))";
				colvarActionName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarActionName);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["Bookstore"].AddSchema("TblPermissions",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public Guid Id 
		{
			get { return GetColumnValue<Guid>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("PermissionsName")]
		[Bindable(true)]
		public string PermissionsName 
		{
			get { return GetColumnValue<string>(Columns.PermissionsName); }
			set { SetColumnValue(Columns.PermissionsName, value); }
		}
		  
		[XmlAttribute("ActionName")]
		[Bindable(true)]
		public byte ActionName 
		{
			get { return GetColumnValue<byte>(Columns.ActionName); }
			set { SetColumnValue(Columns.ActionName, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(Guid varId,string varPermissionsName,byte varActionName)
		{
			TblPermission item = new TblPermission();
			
			item.Id = varId;
			
			item.PermissionsName = varPermissionsName;
			
			item.ActionName = varActionName;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(Guid varId,string varPermissionsName,byte varActionName)
		{
			TblPermission item = new TblPermission();
			
				item.Id = varId;
			
				item.PermissionsName = varPermissionsName;
			
				item.ActionName = varActionName;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn PermissionsNameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn ActionNameColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"Id";
			 public static string PermissionsName = @"PermissionsName";
			 public static string ActionName = @"ActionName";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
