using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bookstore
{
    /// <summary>
    /// Controller class for TblUser
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblUserController
    {
        // Preload our schema..
        TblUser thisSchemaLoad = new TblUser();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblUserCollection FetchAll()
        {
            TblUserCollection coll = new TblUserCollection();
            Query qry = new Query(TblUser.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblUserCollection FetchByID(object Id)
        {
            TblUserCollection coll = new TblUserCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblUserCollection FetchByQuery(Query qry)
        {
            TblUserCollection coll = new TblUserCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblUser.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblUser.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(Guid Id,string UserName,string FirstName,string LastName,string Email,string UserAddress,string UserPassword,DateTime Birthday,string Phone,bool Sex,bool IsActived,bool IsDeleted,string Avatar,string CreatedUser,DateTime CreatedDate,string UpdatedUser,DateTime UpdatedDate)
	    {
		    TblUser item = new TblUser();
		    
            item.Id = Id;
            
            item.UserName = UserName;
            
            item.FirstName = FirstName;
            
            item.LastName = LastName;
            
            item.Email = Email;
            
            item.UserAddress = UserAddress;
            
            item.UserPassword = UserPassword;
            
            item.Birthday = Birthday;
            
            item.Phone = Phone;
            
            item.Sex = Sex;
            
            item.IsActived = IsActived;
            
            item.IsDeleted = IsDeleted;
            
            item.Avatar = Avatar;
            
            item.CreatedUser = CreatedUser;
            
            item.CreatedDate = CreatedDate;
            
            item.UpdatedUser = UpdatedUser;
            
            item.UpdatedDate = UpdatedDate;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(Guid Id,string UserName,string FirstName,string LastName,string Email,string UserAddress,string UserPassword,DateTime Birthday,string Phone,bool Sex,bool IsActived,bool IsDeleted,string Avatar,string CreatedUser,DateTime CreatedDate,string UpdatedUser,DateTime UpdatedDate)
	    {
		    TblUser item = new TblUser();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.UserName = UserName;
				
			item.FirstName = FirstName;
				
			item.LastName = LastName;
				
			item.Email = Email;
				
			item.UserAddress = UserAddress;
				
			item.UserPassword = UserPassword;
				
			item.Birthday = Birthday;
				
			item.Phone = Phone;
				
			item.Sex = Sex;
				
			item.IsActived = IsActived;
				
			item.IsDeleted = IsDeleted;
				
			item.Avatar = Avatar;
				
			item.CreatedUser = CreatedUser;
				
			item.CreatedDate = CreatedDate;
				
			item.UpdatedUser = UpdatedUser;
				
			item.UpdatedDate = UpdatedDate;
				
	        item.Save(UserName);
	    }
    }
}
